- .github/workflows/ci.yml
- README.md
- src/lib.rs
Adds an example on docs.rs and in README.md. This example is part of
rustdoc, hence auto tested.
> docs: use sync readme

- .github/workflows/ci.yml
- Cargo.toml
Soft check, as rusqlite provides no msrv guarantees.
> Minimum Rust version check in CI

- Cargo.toml
Change the `env_logger` dependency to the newest version.
> Update the env_logger dependency

- rusqlite_migration/README.md
Migadu offered discounted service as a part of their policy to support
open-source and non-profits.
> doc: add thanks to Migadu

- .github/workflows/ci.yml
Extracted just the change to `tarpaulin`.
> Change runner to `tarpaulin`

- rusqlite_migration/src/tests/asynch.rs
- rusqlite_migration_tests/tests/async_up_and_down.rs
- rusqlite_migration_tests/tests/lib.rs
Added some additional tests to make sure there won't be any behavior mismatches between the async and the sync versions.
> Additional async tests

- CHANGELOG.md
Cherry picking the changelog update from #70
> doc: add changelog entry for 1.0.2

- .github/workflows/ci.yml
- rusqlite_migration/src/builder.rs
- rusqlite_migration/src/lib.rs
Toughen up the CI checks and make the necessary fixes
> Documentation improvements

- .cargo/mutants.toml
- .github/workflows/ci.yml
- CHANGELOG.md
- rusqlite_migration/Cargo.toml
- rusqlite_migration_tests/Cargo.toml
Prepare for the next alpha version
This also includes some fixes for the CI.
> chore: bump cargo version

- README.md
> doc: misc. improvements

- README.md
- rusqlite_migration/src/errors.rs
- rusqlite_migration/src/lib.rs
This PR fixes various typos found throughout the project.
> Fix typos in the project

- CHANGELOG.md
- README.md
- rusqlite_migration/Cargo.toml
> doc: Prepare changelog for version 1.1.0

- CHANGELOG.md
- README.md
- rusqlite_migration/Cargo.toml
Update changelog and Cargo.toml
> chore: bump version to 1.2.0 Beta 1

- README.md
Put them one per line, it’s more readable and works on GitHub and the
homepage.
Add some markup for the homepage.
> docs: badges improvement

- CHANGELOG.md
- README.md
- rusqlite_migration/Cargo.toml
Will merge after feedback [1] on the beta.
[1]: https://github.com/cljoly/rusqlite_migration/discussions/149
> Bump to version 1.2.0

- rusqlite_migration/src/lib.rs
> docs: fix indentation

- rusqlite_migration/src/lib.rs
Explicitly document that the `extra_check` feature of rusqlite will
cause errors to be returned if a migration returns anything. This is, I
think, why people use that feature.
Also document what happens on rusqlite errors during statement
execution.
Fixes #134
> docs: document what happens with extra_check

- rusqlite_migration/src/tests/helpers.rs
> test: fix typo in feature name

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
This commit will be used to release a new version
> doc: update changelog & bump cargo version

- rusqlite_migration/src/builder.rs
- rusqlite_migration/src/lib.rs
- rusqlite_migration/src/loader.rs
- Remove needless lifetimes https://rust-lang.github.io/rust-clippy/master/index.html#needless_lifetimes
> chore: clippy fixes

- README.md
Note: use a permalink for lazy_static as we can now replace it with
lazy_lock (#177)
> docs(README): link to examples and other tweaks

- .github/workflows/ci.yml
This entails some breaking changes, but should be ok here:
https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes
> chore: update GH upload-artifact

- Cargo.lock
- examples/async/Cargo.toml
- examples/async/src/main.rs
- examples/from-directory/Cargo.toml
- examples/simple/Cargo.toml
- rusqlite_migration/Cargo.toml
- rusqlite_migration_tests/Cargo.toml
https://github.com/cljoly/rusqlite_migration/pull/223
> chore(deps): use tokio-rusqlite-new and bump rusqlite to 0.34

- CHANGELOG.md
- README.md
Also link to it from the README, as advised in the [API
guidelines](https://rust-lang.github.io/api-guidelines/documentation.html#release-notes-document-all-significant-changes-c-relnotes).
> doc: update changelog for 2.0

- rusqlite_migration/src/lib.rs
- rusqlite_migration/src/tests/core.rs
This is a slightly different take on #170, where instead of returning
the total number of migrations defined, we return the number of
migrations defined, but not yet applied.
Going back to the discussion in #170, what we actually need is:
1. tell whether migrations will be run, without actually running them.
One use of this information is to run a backups before applying the
migrations.
2. [“see the version difference somehow”][diff], i.e. the number of
migrations to be applied.
Thus I think that returning the number of migrations to be applied,
instead of the number of migrations already applied fulfills the need
better. And it is less of a foot gun in my opinion:
1. The index in the vector of migration is off by one compared to the
index in the user version, which is the one exposed by …
> feat: expose the number of migrations to be applied

- Cargo.lock
- Cargo.toml
Post release version bump
- **chore: update locked dependencies**
- **chore: bump cargo version**
> Bump cargo version

- .github/workflows/ci.yml
See
https://docs.github.com/en/actions/tutorials/authenticate-with-github_token
for reference.
> ci: scope GitHub API tokens
