cljoly/rusqlite_migration

Cargo.toml, examples/quick_start.rs, src/lib.rs, src/tests.rs, tests/multiline_test.rs
- Use `execute_batch` to allow for multiline statements
- It turns out that PRAGMAs are not always working well from inside a
transaction, updated the documentation to make that clearer
Fixes #2
=> feat: support multi line SQL statements in migrations

.gitignore, Cargo.toml, src/errors.rs, src/lib.rs, tests/integration_test.rs, tests/multiline_test.rs, tests/up_and_down.rs
Implementation of `.down()` as discussed in #5.
- Errors moved to their own module. There is a public re-export so nothing will break, it just makes the code easier to navigate.
- Added `.down()` method on migrations
- Added `.to_version()` method for migrating to an arbitrary version
- Added logging to integration tests, this makes debugging much easier. One new dev dependency.
- Improve logging somewhat
- New error variants
- Deprecated and hidden `MigrateToLowerNotSupported`. It's kept for back-compat, ideally should be removed.
I split it to smaller commits, so you can cherry-pick if you like, but I think all the changes make sense
Some things I noticed:
- If `SchemaVersion::Inside` was not off-by-one, it would be more straightforward to use. `.to_version()` uses the natural version …
=> Rollback support / migrate to arbitrary version

src/errors.rs, src/lib.rs, src/tests.rs, tests/integration_test.rs, tests/multiline_test.rs, tests/up_and_down.rs
Use an Option<usize> to reflect the fact that we either have a corresponding migration, or we don’t and we want to remove all migrations ever applied.
Closes #8
The main change is:
```
-    pub fn to_version(&self, conn: &mut Connection, version: usize) -> Result<()> {
+    pub fn to_version(&self, conn: &mut Connection, version: Option<usize>) -> Result<()> {
```
=> feat(#8): attempt to simplify to_version

src/errors.rs, src/lib.rs, src/tests.rs
When we encounter a database whose migration number is higher than the
highest migration, we currently panic. With this change, we just return
an error.
Fixes #17
=> fix: error instead of panicking on higher migration level

src/errors.rs, src/lib.rs, src/tests.rs
This implements a method to validate that all foreign keys are still valid after a migration as discussed in #4.
~This still lacks tests, feel free to comment on anything else.~
=> Add foreign_key_check method to migrations

src/lib.rs
- docs: fix doc tests
- chore: fix clippy warning
=> Misc. test fixes

.github/workflows/ci.yml, Cargo.toml, src/errors.rs, src/lib.rs, src/tests.rs
Draft PR to make discussion/review a bit easier.
=> Add up/down hooks to insert custom Rust code

Cargo.toml
Add the missing `repository` metadata. This makes browsing between `crates.io`, `docs.rs` and this repo easier.
=> Update repository metadata

README.md, clippy.toml, src/errors.rs, src/lib.rs
This PR fixes all warnings with `-W clippy::pedantic` except for the potential truncation/sign loss problems.
=> Fix pedantic warnings

README.md, src/lib.rs
- style: silence some clippy pedantic warnings
- docs: fix links in the example
cc @matze this builds on #38
=> Follow-up on clippy pedantic warnings

rusqlite_migration/src/asynch.rs
The documentation was incorrectly stating that this method "adapts" something, when it creates a proxy.
=> Fix `AsyncMigrations::new` documentation

.github/workflows/ci.yml, examples/async/src/main.rs
The `async` example had an incorrect test. Fixed it and also added an new CI pipeline to verify the examples so it cannot happen in the future.
=> Fix example test

.github/workflows/ci.yml
Various attempts to implement coverage upload to coveralls (codecov failed to reactivate the repo).
It does not seem to work, but perhaps we need to have at least one build from a PR or the master branch?
=> Attempt to implement coverage reports

.github/workflows/ci.yml
* Remove doc-tests coverage, as we then lose the report on covered lines
in source files by coveralls
* Exclude the module `asynch` as it is mostly tested by doc-tests, to
ease maintainability and limit duplicated code.
=> Tweak coverage parameters

rusqlite_migration/src/lib.rs, rusqlite_migration/src/tests/synch.rs
With hooks, since the address of the underlying closure is used for
comparison, it is helpful to include it in the debug output.
=> test: test Eq implementations

README.md, rusqlite_migration/src/lib.rs
It’s quite counter-intuitive to have to change the lib.rs file to change
the README.md file. This is now explained in the “Contributing” section
of the readme.
=> doc: explain cargo sync-readme to contributors

README.md
It’s super long now and it takes two lines on the homepage (https://cj.rs/rusqlite_migration/).
=> doc: remove a badge from README

rusqlite_migration/src/errors.rs, rusqlite_migration/src/lib.rs, rusqlite_migration/src/tests/synch.rs, rusqlite_migration_tests/tests/up_and_down.rs
* A string was manually copied to create an error, so the error could
become inaccurate as the string may become out of date.
* Use `with_sql` method when possible without incurring extra allocation
* Fix typo in documentation
* Improve some logging directive (in particular, inlining the variables)
=> refactor: misc. style and robustness improvements

rusqlite_migration/src/loader.rs
Limit intermediary allocations (remove one intermediary `Vec` allocation
in particular) and generally try to limit the computation performed.
Fixes #76
=> refactor: improve the performance of from_directory

rusqlite_migration/src/lib.rs
We are now implementing the standard `FromIterator` trait.
=> refactor!: deprecate `Migrations::from_iter`

README.md
Currently, we report on the status of the dependencies in the dev
version (i.e. the lastest master commit of the GitHub repository). This
a bit misleading, because users of the library usually pull the latest
stable and use it. Whether dependencies are up to date for the latest
stable is quite different from the dev version.
This updated URL reports on the latest version. The drawback is that one
has to manually update the path when a new stable version is released.
=> doc: make the deps badge more accurate

.github/workflows/ci.yml, CHANGELOG.md, examples/async/Cargo.toml, examples/from-directory/Cargo.toml, examples/simple/Cargo.toml, rusqlite_migration/Cargo.toml, rusqlite_migration/benches/from_directory.rs, rusqlite_migration/benches/iai.rs, rusqlite_migration/src/asynch.rs, rusqlite_migration/src/errors.rs, rusqlite_migration/src/lib.rs, rusqlite_migration/src/tests/builder.rs, rusqlite_migration/src/tests/synch.rs, rusqlite_migration_tests/Cargo.toml, rusqlite_migration_tests/tests/async_from_directory_test.rs, rusqlite_migration_tests/tests/async_up_and_down.rs, rusqlite_migration_tests/tests/multiline_test.rs
Migrate `tokio-rusqlite` to the newest version handling the new `ConnectionClosed` error condition.
=> Migrate to the newest tokio-rusqlite

rusqlite_migration/src/errors.rs
Fix ConnectionClosed mapping when `async-tokio-rusqlite` is disabled.
=> Fix ConnectionClosed mapping

rusqlite_migration/src/loader.rs
Implements the performance improvements described in #85 i.e. replacing the `BTreeMap` with a `Vec` of `Option`.
Closes #85.
=> Replace BTreeMap with Vec

rusqlite_migration/src/builder.rs, rusqlite_migration/src/lib.rs, rusqlite_migration/src/loader.rs, rusqlite_migration/src/tests/builder.rs
This PR implements my take on #86. The edit api now takes ownership of the migration it edits.
Closes #86
=> Improve edit api

examples/async/Cargo.toml, examples/from-directory/Cargo.toml, examples/simple/Cargo.toml, rusqlite_migration/Cargo.toml, rusqlite_migration/src/lib.rs, rusqlite_migration_tests/Cargo.toml
Changes the minimal supported `rusqlite` version to `0.29.0`. 
Closes #69
=> Require new version of rusqlite

rusqlite_migration/src/lib.rs
This is not `dead_code` any more, since this field is used.
Closes #75
=> Remove unnecessary dead_code markers

rusqlite_migration/src/tests/asynch.rs, rusqlite_migration/src/tests/helpers.rs, rusqlite_migration/src/tests/mod.rs, rusqlite_migration/src/tests/synch.rs
Extract helper methods to their own module shared between `synch` and `asynch` tests.
Closes #98
=> Extract test helper methods

.cargo/mutants.toml, .github/workflows/ci.yml, rusqlite_migration/src/errors.rs, rusqlite_migration/src/tests/mod.rs
This is done by a mix of improved tests and pinning of cargo mutants so that it plays nicely with the features of the crate.
=> Fix cargo-mutants in CI

rusqlite_migration/benches/iai.rs, rusqlite_migration/src/lib.rs, rusqlite_migration/src/tests/asynch.rs, rusqlite_migration/src/tests/helpers.rs, rusqlite_migration/src/tests/synch.rs, rusqlite_migration_tests/tests/async_up_and_down.rs
This change enables `foreign_key_check` for downward migrations.
TODO:
Closes #4.
=> Make down migrations respect the `foreign_key_check` setting

Cargo.toml, rusqlite_migration/Cargo.toml, rusqlite_migration_tests/Cargo.toml, rusqlite_migration_tokio_async/Cargo.toml, rusqlite_migration_tokio_async/README.md, rusqlite_migration_tokio_async/src/lib.rs
This is a first step towards #110, as it allows to reserve the package name on crates.io
=> chore: refactor cargo manifests and add pkg

examples/from-directory/Cargo.toml, examples/simple/Cargo.toml, rusqlite_migration/Cargo.toml, rusqlite_migration_tests/Cargo.toml
Pinning the dependency to the exact version `0.30.0` is unnecessary because Cargo doesn't consider 0.30 and 0.31 compatible (Cargo's modified semver considers the first non-zero component of the version as the "major" number that determines compatibility). In addition, pinning to an exact version can prevent an update to an in-theory-compatible 0.30.1 and even cause unresolvable dependency conflicts in downstream packages. To be fair however, rusqlite doesn't seem to use the patch component of the version number anyway so this wouldn't happen in practice.
=> Don't pin to exact rusqlite version

.cargo/mutants.toml, .github/workflows/ci.yml, rusqlite_migration/Cargo.toml, rusqlite_migration/src/builder.rs, rusqlite_migration/src/errors.rs, rusqlite_migration/src/lib.rs, rusqlite_migration/src/loader.rs, rusqlite_migration/src/tests/builder.rs, rusqlite_migration/src/tests/snapshots/rusqlite_migration__tests__builder__len_builder.snap, rusqlite_migration/src/tests/snapshots/rusqlite_migration__tests__builder__valid_index.snap, rusqlite_migration/src/tests/snapshots/rusqlite_migration__tests__synch__migration_hook_debug.snap, rusqlite_migration/src/tests/synch.rs
Newer versions now build on the codebase. The only issue is that there are some more mutants to catch.
=> Stop installing an old cargo mutants in CI

CHANGELOG.md, README.md, rusqlite_migration/src/errors.rs, rusqlite_migration/src/lib.rs, rusqlite_migration/src/tests/helpers.rs, rusqlite_migration/src/tests/snapshots/rusqlite_migration__tests__synch__error_display-2.snap, rusqlite_migration/src/tests/snapshots/rusqlite_migration__tests__synch__error_display-3.snap, rusqlite_migration/src/tests/snapshots/rusqlite_migration__tests__synch__error_display-4.snap, rusqlite_migration/src/tests/snapshots/rusqlite_migration__tests__synch__error_display-5.snap, rusqlite_migration/src/tests/snapshots/rusqlite_migration__tests__synch__error_display.snap, rusqlite_migration/src/tests/snapshots/rusqlite_migration__tests__synch__invalid_fk_check_test.snap, rusqlite_migration/src/tests/synch.rs
Call out:
* Use of the library with insta (insta.rs)
* Useful caro tools to install to debug failing CI
Does some of the documentation work for #112
=> doc: mention cargo-insta in the Readme

rusqlite_migration/Cargo.toml, rusqlite_migration/src/lib.rs
Features of the crate aren’t shown in the generated doc. Add a cargo
feature to trigger the right nightly option to do that.
=> doc: make docs.rs show features

.github/workflows/ci.yml
Use the newly introduced feature to force color output in CI. More
enhancements (e.g. [sharding][1]) may be implemented in the future.
Now that Cargo.lock is committed, install cargo-mutants based on the
content of the lock file.
[1]: https://mutants.rs/shards.html?highlight=shard#sharding
=> chore: update cargo-mutants to version 24.2.1

.github/workflows/ci.yml, rusqlite_migration/src/tests/synch.rs, rusqlite_migration_tokio_async/src/lib.rs
The mutants were:
```
MISSED   rusqlite_migration_tokio_async/src/lib.rs:2:10: replace + with * in add in 0.2s build + 0.1s test
MISSED   rusqlite_migration/src/lib.rs:535:35: replace - with + in Migrations<'m>::goto_down in 0.9s build + 1.5s test
```
While we are here, shard mutants to avoid waiting for too long on CI.
=> test: add tests to catch 2 mutants

examples/from-directory/build.rs
This allows `cargo build` to rebuild correctly when there are modified or new migrations without any code changes.
=> Add build.rs with `rerun-if-changed` for migrations directory

CHANGELOG.md, Cargo.toml, rusqlite_migration/Cargo.toml, rusqlite_migration/benches/criterion.rs, rusqlite_migration/benches/iai.rs, rusqlite_migration/build.rs, rusqlite_migration/src/lib.rs, rusqlite_migration_tokio_async/Cargo.toml, rusqlite_migration_tokio_async/src/lib.rs
- Bump edition to 2021
- Refresh cargo manifests (in particular, factor out linter directives)
=> Update Cargo.toml files to use recent features

rusqlite_migration/Cargo.toml, rusqlite_migration_tests/Cargo.toml
Updates the version of `rusqlite` used to `0.31`. Usually this would not be a big deal, but the shipped version of `libsqlite3` has been updated to `0.28`, which conflicts with the version `0.27` shipped with `rusqlite 0.30`.
This is the error caused by the conflict:
```
rust-analyzer failed to load workspace: Failed to load the project at /home/lenndg/projects/quickplan/server/Cargo.toml: Failed to read Cargo metadata from Cargo.toml file /home/lenndg/projects/quickplan/server/Cargo.toml, Some(Version { major: 1, minor: 76, patch: 0 }): Failed to run `cd "/home/lenndg/projects/quickplan/server" && RUSTUP_TOOLCHAIN="/home/lenndg/.rustup/toolchains/stable-x86_64-unknown-linux-gnu" "/home/lenndg/.cargo/bin/cargo" "metadata" "--format-version" "1" "--manifest-path" …
```
=> Rusqlite update to latest version (0.31)

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, README.md, examples/Cargo.toml, examples/async/Cargo.toml, examples/async/src/main.rs, examples/from-directory/Cargo.toml, examples/simple/Cargo.toml, rusqlite_migration/src/lib.rs, rusqlite_migration_tests/Cargo.toml, rusqlite_migration_tests/tests/multiline_test.rs
WIP PR to fix the problem raised in https://github.com/cljoly/rusqlite_migration/issues/15#issuecomment-1868524798:
> Hi there, first of all thanks for your work!
> I just stumbled across this line on the top level documentation of the crate:
> 
> conn.pragma_update(None, "journal_mode", &"WAL").unwrap();
> 
> This panics for me with ExecuteReturnedResults. According to this issue in rusqlite we have to use pragma_update_and_check instead.
> 
> So probably the easiest way to fix the documentation would be to change that line to:
> conn.pragma_update_and_check(None, "journal_mode", &"WAL", |_| Ok(())).unwrap();
=> Fix broken docs and examples when some rusqlite features are used

README.md
This makes text more readable, because it’s not interupted by long URLs.
=> doc: use link references in markdown

examples/from-directory/Cargo.toml, rusqlite_migration/Cargo.toml
- Sort dependencies
- Transform multi-line inline table into tables, as the spec requires
for readability [1]:
> Inline tables are intended to appear on a single line. […] No
> newlines are allowed between the curly braces unless they are valid
> within a value. Even so, it is strongly discouraged to break an
> inline table onto multiples lines. If you find yourself gripped
> with this desire, it means you should be using standard tables.
[1] https://toml.io/en/v1.0.0#inline-table
=> chore: clean-up Cargo.toml

rusqlite_migration/src/asynch.rs
This avoids some needless cloning. This change should be API compatible.
This was written by @fluffysquirrels, I have just extracted the code from #171
=> fix: wrap migrations from AsyncMigrations in Arc

Cargo.lock, Cargo.toml, rusqlite_migration/Cargo.toml, rusqlite_migration_tests/Cargo.toml, rusqlite_migration_tokio_async/Cargo.toml
Cargo.toml have inconsistent metadata (version numbers, website,
license, repo…). Define these in the workspace and import them from the
packages.
To check that no key was changed in the main package, the output of
```
cargo read-manifest --manifest-path rusqlite_migration/Cargo.toml
```
was checked before and after this commit and it was identical.
=> refactor: Use workspace features for consistency

.github/workflows/ci.yml, CHANGELOG.md, Cargo.toml
This cherry picks some changes from #181 and updates the changelog, because these changes can live in the master branch. The intent is for the branch of `v1.3.0 Alpha-Without-Tokio 1` to only carry the commits removing the actual feature.
- **docs: update changelog for v1.3.0 Alpha-Without-Tokio 1**
- **chore: bump MSRV to 1.77.0**
=> Prepare an alpha version without tokio features

Cargo.lock, Cargo.toml, examples/async/Cargo.toml, examples/from-directory/Cargo.toml, examples/simple/Cargo.toml, rusqlite_migration/Cargo.toml, rusqlite_migration/src/lib.rs, rusqlite_migration_tests/Cargo.toml
This PR aims to introduce a long term solution to update rusqlite to v0.33. If you need an updated version now, there is a stopgap [alpha version](https://github.com/cljoly/rusqlite_migration/releases/tag/v1.3.0-alpha-without-tokio.1) that you might be able to use.
******************
Changelog at https://github.com/rusqlite/rusqlite/releases/tag/v0.32.0
Concerns:
default transaction behavior can interfer with the migrations?
* Yes, but I don’t think it matters, because all behaviors can work. Presumably, if someone uses a particular behaviors, they want it to apply also for migrations.
=> chore! Update rusqlite to v0.33

README.md
This feature seem to have been added recently. It’s nice because I
always forget to update this (for instance in the last release 1.3.0).
=> doc: make dep.rs badge point to latest commit

rusqlite_migration/src/tests/synch.rs
Even though the function is deprecated, the code is still present and we
don’t want it to break unexpectedly.
=> test: add a test for new_iter

.github/workflows/ci.yml
Had to pin it to 22.04 in #217, let's try to bump it back up now.
=> chore: Use ubuntu-latest in CI

.github/workflows/ci.yml
Turns out that "on: pull_request" triggers runs on non-code changes,
which is not useful here:
> Runs your workflow when activity on a pull request in the workflow's repository occurs. For example, if no activity types are specified, the workflow runs when a pull request is opened or reopened or when the head branch of the pull request is updated
https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request
Push should be enough and should apply on forks as well: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#push
=> chore: further tweak CI trigger logic

.github/workflows/ci.yml, CHANGELOG.md, Cargo.toml, README.md
Starting with version [0.33](https://github.com/rusqlite/rusqlite/releases/tag/v0.33.0),
rusqlite has a policy for the minimum supported rust version (see https://github.com/rusqlite/rusqlite/pull/1576).
Align our MSRV and rusqlite’s, if rusqlite doesn’t support a particular
version (i.e. doesn’t compile), then rusqlite_migration can’t be used
either.
We could try to figure out what version of Rust still compiles with
rusqlite, beyond their official MSRV, but that’s easy to get wrong and
an additional support burden on us.
Now, for now it means that the MSRV is effectively the latest Rust
version, but that should change as new releases of Rust become stable
(i.e. if 1.85 gets out before rusqlite gets a new version, we will again
have a MSRV that’s not the latest stable Rust). Thus, it’s …
=> chore(msrv): align MSRV with rusqlite

CHANGELOG.md, rusqlite_migration/src/lib.rs, rusqlite_migration/src/tests/synch.rs
This has been deprecated for a while now, remove it along with the other
breaking changes (#39).
=> refactor!: remove `Migrations::new_iter`

examples/async/src/main.rs, examples/from-directory/build.rs, examples/from-directory/src/main.rs, examples/simple/src/main.rs, rusqlite_migration/benches/criterion.rs, rusqlite_migration/benches/from_directory.rs, rusqlite_migration/benches/iai.rs, rusqlite_migration/build.rs, rusqlite_migration/src/builder.rs, rusqlite_migration/src/errors.rs, rusqlite_migration/src/errors/tests.rs, rusqlite_migration/src/lib.rs, rusqlite_migration/src/loader.rs, rusqlite_migration/src/tests/builder.rs, rusqlite_migration/src/tests/helpers.rs, rusqlite_migration/src/tests/mod.rs, rusqlite_migration/src/tests/synch.rs, rusqlite_migration_tests/tests/from_directory_test.rs, rusqlite_migration_tests/tests/integration_test.rs, rusqlite_migration_tests/tests/lib.rs, rusqlite_migration_tests/tests/migrations_builder_from_iterator_test.rs, rusqlite_migration_tests/tests/migrations_builder_test.rs, rusqlite_migration_tests/tests/multiline_test.rs, rusqlite_migration_tests/tests/up_and_down.rs
This is in line with [the guidelines][notices]. In particular:
- I did not alter anyone else’s copyright notices, only my own.
- Fine grained copyright ownership is tracked in Git.
We also specify the license with an SPDX License Identifier (along with
the license notices). This is NOT a license change.
[notices]: https://cj.rs/open-source/docs/contribute/#copyright-notices
=> chore: update copyright and license notices

CHANGELOG.md, README.md, examples/async/src/main.rs, examples/simple/src/main.rs, rusqlite_migration/src/lib.rs, rusqlite_migration/src/tests/core.rs
This builds on https://github.com/cljoly/rusqlite_migration/pull/251 and
proposes another path. Like #251, it provides a method to store the
migrations in a `const` context, but:
* it does so without breaking changes, at least compared to the latest
release: `new` is not const anymore, but that change was not released
in a stable version.
* exposes only concrete types like `Vec` and slices to build the
migrations, instead of the discussed `impl Into<Cow<'m, [M<'m>]>>`.
This should make the compiler report clearer errors, improving
usability.
* we can still easily built from a `Cow` type, by borrowing it.
Drawbacks
---------
The main drawback I can think of is this: the most intuitive function to
call (`new`) takes a `Vec`, while it would be better to just use a slice
(which `from_slice` …
=> refactor: Keep migrations in `Cow` instead of `Vec`

rusqlite_migration/src/lib.rs
This changes the `Migrations::from_slice` documentation a bit. `Migrations::new` can be used in a `const` context, so the current text isn't accurate.
I also took the opportunity to add a `const` example. Is it OK?
=> docs: improve `Migrations::from_slice` documentation

CHANGELOG.md, Cargo.lock, Cargo.toml, examples/async/Cargo.toml, examples/from-directory/Cargo.toml, examples/simple/Cargo.toml, rusqlite_migration/Cargo.toml, rusqlite_migration_tests/Cargo.toml
For the update of `tokio-rusqlite-new` in the async example (which users
may import based on the guidance in this example), I have once again
looked at the diff and I did not spot anything:
```sh
diff -U 3 -x Cargo.lock ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-rusqlite-new-0.8.0/ ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-rusqlite-new-0.9.0/
```
output:
```diff
diff -U 3 -x Cargo.lock /home/cj/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-rusqlite-new-0.8.0/.cargo_vcs_info.json /home/cj/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-rusqlite-new-0.9.0/.cargo_vcs_info.json
--- /home/cj/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-rusqlite-new-0.8.0/.cargo_vcs_info.json	1970-01-01 00:00:01.000000000 +0000
+++ …
```
=> Version 2.1.0

Cargo.toml
Crates.io uses that to display a “Documentation” link in search results
(and presumably other places).
=> chore: add docs.rs link to Cargo metadata

rusqlite_migration/src/errors/tests.rs
Newer versions of `cargo mutants` (25.0.1) find that removing some of
the match arms doesn’t make the tests fail. Effectively, the tests don’t
check if we are doing anything more than the fallback enum comparison.
Mutants found:
```
MISSED   rusqlite_migration/src/errors.rs:63:13: delete match arm in 0.7s build + 0.7s test
MISSED   rusqlite_migration/src/errors.rs:65:13: delete match arm in 0.6s build + 0.7s test
```
=> test: test error equality more thoroughly

rusqlite_migration/src/lib.rs, rusqlite_migration/src/tests/core.rs, rusqlite_migration/src/tests/helpers.rs, rusqlite_migration/src/tests/snapshots/rusqlite_migration__tests__builder__len_builder.snap, rusqlite_migration/src/tests/snapshots/rusqlite_migration__tests__builder__valid_index.snap, rusqlite_migration/src/tests/snapshots/rusqlite_migration__tests__core__all_valid_down_test.snap, rusqlite_migration/src/tests/snapshots/rusqlite_migration__tests__core__all_valid_up_test.snap, rusqlite_migration/src/tests/snapshots/rusqlite_migration__tests__core__invalid_fk_check_test.snap, rusqlite_migration/src/tests/snapshots/rusqlite_migration__tests__core__migration_hook_debug.snap, rusqlite_migration/src/tests/snapshots/rusqlite_migration__tests__core__read_only_db_all_valid.snap, rusqlite_migration/src/tests/snapshots/rusqlite_migration__tests__core__user_version_error.snap
This will also be useful when we introduce optional validation of
downward migrations (#113)
=> test: refactor tests, adding downward migrations

rusqlite_migration/src/lib.rs, rusqlite_migration/src/tests/core.rs, rusqlite_migration/src/tests/snapshots/rusqlite_migration__tests__core__everything.snap, rusqlite_migration/src/tests/snapshots/rusqlite_migration__tests__core__everything_alt.snap, rusqlite_migration/src/tests/snapshots/rusqlite_migration__tests__core__everything_compact_debug.snap, rusqlite_migration/src/tests/snapshots/rusqlite_migration__tests__core__everything_debug.snap, rusqlite_migration/src/tests/snapshots/rusqlite_migration__tests__core__up_down.snap, rusqlite_migration/src/tests/snapshots/rusqlite_migration__tests__core__up_down_alt.snap, rusqlite_migration/src/tests/snapshots/rusqlite_migration__tests__core__up_down_fk.snap, rusqlite_migration/src/tests/snapshots/rusqlite_migration__tests__core__up_down_fk_alt.snap, rusqlite_migration/src/tests/snapshots/rusqlite_migration__tests__core__up_only.snap, rusqlite_migration/src/tests/snapshots/rusqlite_migration__tests__core__up_only_alt.snap
This is helpful when M is embedded in errors and just generally for
users. This representation is for humans and we do not implement
FromStr, we could change this in the future without causing a breaking
change.
See also [this opinion in an old Rust discussion thread][1]:
> my final answer to "is changing Display's output breaking" is "no if
> it's an Error, yes if it's FromStr, and you're doing it wrong
> otherwise."
[1]: https://users.rust-lang.org/t/are-changes-to-fmt-display-considered-breaking/59775/7
=> feat: implement Display for M

CHANGELOG.md, Cargo.lock, Cargo.toml, examples/async/Cargo.toml, examples/from-directory/Cargo.toml, examples/simple/Cargo.toml, rusqlite_migration/Cargo.toml, rusqlite_migration_tests/Cargo.toml
Rusqlite changelog: https://github.com/rusqlite/rusqlite/releases/tag/v0.36.0
tokio-rusqlite-new diffs (looks fine):
```
diff -r -u --color=auto -x Cargo.lock ~/.cargo/registry/src/index.crates.io-*/tokio-rusqlite-new-0.{9.0/,10.0/}
```
```diff
diff -r -u '--color=auto' -x Cargo.lock /home/cj/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-rusqlite-new-0.9.0/.cargo_vcs_info.json /home/cj/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-rusqlite-new-0.10.0/.cargo_vcs_info.json
--- /home/cj/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-rusqlite-new-0.9.0/.cargo_vcs_info.json	1970-01-01 00:00:01.000000000 +0000
+++ /home/cj/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-rusqlite-new-0.10.0/.cargo_vcs_info.json	1970-01-01 00:00:01.000000000 +0000 …
```
=> chore: update rusqlite and tokio-rusqlite-new

rusqlite_migration/build.rs, rusqlite_migration/src/lib.rs
This is a new warning, presumably with Rust 1.88.
=> chore: fix clippy direct format strings

CHANGELOG.md, Cargo.lock, Cargo.toml, examples/async/Cargo.toml, examples/from-directory/Cargo.toml, examples/simple/Cargo.toml, rusqlite_migration/Cargo.toml, rusqlite_migration_tests/Cargo.toml
=> chore: update rusqlite and bump version number

Cargo.lock, examples/async/Cargo.toml, examples/from-directory/Cargo.toml, examples/simple/Cargo.toml, rusqlite_migration/Cargo.toml, rusqlite_migration_tests/Cargo.toml
Looking at the report from `cargo t --timings`, `jiff` is one of the
longuest dependencies to build. It turns out that it is an optional
depenency of `env_logger`. This prompted me to go over a few of the
costliest dependencies that could be removed by opting out of default
dependencies.
* `env_logger`: we don’t really care about filtering, colored output,
human times... most of the time.
* `simple-logging`: this is not used anymore and the feature of
`env_logger` are useful sometimes, so no reason to go back to
`simple-logging`.
* `criterion`: we rarely look at the benchmark output, we can enable the
additional features temporarily only then.
Before the change, using `hyperfine -p 'cargo clean' 'cargo t'`:
```
Benchmark 1: cargo t
Time (mean ± σ):     12.463 s ±  0.188 s    [User: 83.399 …
```
=> test: improve build time by removing some unused optional deps

rusqlite_migration_tests/tests/from_directory_test.rs, rusqlite_migration_tests/tests/migrations/no_leading_zero/1-t1/up.sql, rusqlite_migration_tests/tests/migrations/no_leading_zero/10-t10/up.sql, rusqlite_migration_tests/tests/migrations/no_leading_zero/11-t11/up.sql, rusqlite_migration_tests/tests/migrations/no_leading_zero/12-t12/up.sql, rusqlite_migration_tests/tests/migrations/no_leading_zero/2-t2/up.sql, rusqlite_migration_tests/tests/migrations/no_leading_zero/3-t3/up.sql, rusqlite_migration_tests/tests/migrations/no_leading_zero/4-t4/up.sql, rusqlite_migration_tests/tests/migrations/no_leading_zero/5-t5/up.sql, rusqlite_migration_tests/tests/migrations/no_leading_zero/6-t6/up.sql, rusqlite_migration_tests/tests/migrations/no_leading_zero/7-t7/up.sql, rusqlite_migration_tests/tests/migrations/no_leading_zero/8-t8/up.sql, rusqlite_migration_tests/tests/migrations/no_leading_zero/9-t9/up.sql
When defining migrations from a directory, the example pads the
migration id with leading zeros. While this is a good practice, if a
user doesn’t do that, we still accept the migrations and process them in
numerical order (which is not the lexicographic order, i.e. 1, 10, 2,
20, 3, 4...).
Add a test to capture both that this is valid and handled in numerical
order. This is both for completeness of the test suite and in case we
change the implementation (e.g. #288).
=> test: add a test for the no leading 0 case
